
name: OpenPDF checkstyle
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  checkstyle_job:
    runs-on: ubuntu-24.04
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Disable IPv6 (runner IPv4-only)
      working-directory: ${{ github.workspace }}
      run: |
        sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
        sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        checkstyle_config: 'checkstyle.xml'
        reporter: 'github-pr-check'